apiVersion: batch/v1
kind: Job
metadata:
  name: metrics-job
  labels:
    app: metrics
spec:
  template:
    metadata:
      labels:
        app: metrics
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/csu-tide
                operator: Exists
      containers:
      - name: metrics
        image: ghcr.io/sdsu-research-ci/rci-metrics:latest
        resources:
          limits:
            cpu: 6
            memory: 16Gi
          requests:
            cpu: 5
            memory: 14Gi
        env:
        - name: CONFIG_FILE
          value: /app/secret-config/config.yaml
        volumeMounts:
        - name: metrics-pvc
          mountPath: /app/io/
        - name: metrics-config-secret
          mountPath: /app/secret-config/
          readOnly: true
      volumes:
      - name: metrics-pvc
        persistentVolumeClaim:
          claimName: metricspvc
      - name: metrics-config-secret
        secret:
          secretName: metrics-config-secret

